// utils/constants.js
export const TRANSPORT_TYPES = {
  BUS: 'Bus',
  TRAIN: 'Train',
  METRO: 'Metro',
  FERRY: 'Ferry',
};

export const MOCK_TRANSPORT_DATA = [
  {
    id: 1,
    route: 'Route 101',
    type: 'Bus',
    from: 'Central Station',
    to: 'Airport Terminal',
    duration: '45 mins',
    price: '$5.50',
    frequency: 'Every 15 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=400',
    description: 'Express bus service connecting city center to airport with comfortable seating.',
    operator: 'City Transit',
    schedule: ['6:00 AM', '6:15 AM', '6:30 AM', '6:45 AM'],
  },
  {
    id: 2,
    route: 'Blue Line',
    type: 'Metro',
    from: 'Downtown',
    to: 'Suburbs East',
    duration: '32 mins',
    price: '$3.00',
    frequency: 'Every 8 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1581262177000-8c89f0f95b63?w=400',
    description: 'Modern metro line with air-conditioned coaches and WiFi connectivity.',
    operator: 'Metro Services',
    schedule: ['5:30 AM', '5:38 AM', '5:46 AM', '5:54 AM'],
  },
  {
    id: 3,
    route: 'Express 205',
    type: 'Train',
    from: 'North Station',
    to: 'South Harbor',
    duration: '1 hour 15 mins',
    price: '$8.00',
    frequency: 'Every 30 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400',
    description: 'High-speed train service with scenic coastal views and onboard refreshments.',
    operator: 'National Rail',
    schedule: ['7:00 AM', '7:30 AM', '8:00 AM', '8:30 AM'],
  },
  {
    id: 4,
    route: 'Ferry F1',
    type: 'Ferry',
    from: 'Main Pier',
    to: 'Island Terminal',
    duration: '25 mins',
    price: '$6.50',
    frequency: 'Every 20 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1593946326398-28e8d2e86d6d?w=400',
    description: 'Scenic ferry route across the bay with outdoor seating and refreshments.',
    operator: 'Bay Ferries',
    schedule: ['8:00 AM', '8:20 AM', '8:40 AM', '9:00 AM'],
  },
  {
    id: 5,
    route: 'Route 45',
    type: 'Bus',
    from: 'University Campus',
    to: 'Shopping District',
    duration: '20 mins',
    price: '$2.50',
    frequency: 'Every 10 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400',
    description: 'Popular student route with frequent service during peak hours.',
    operator: 'City Transit',
    schedule: ['7:00 AM', '7:10 AM', '7:20 AM', '7:30 AM'],
  },
  {
    id: 6,
    route: 'Green Line',
    type: 'Metro',
    from: 'West Terminal',
    to: 'Business Park',
    duration: '28 mins',
    price: '$3.50',
    frequency: 'Every 12 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1581262177000-8c89f0f95b63?w=400',
    description: 'Efficient metro service serving major business districts.',
    operator: 'Metro Services',
    schedule: ['6:00 AM', '6:12 AM', '6:24 AM', '6:36 AM'],
  },
  {
    id: 7,
    route: 'Coastal Express',
    type: 'Train',
    from: 'City Central',
    to: 'Beach Resort',
    duration: '50 mins',
    price: '$7.00',
    frequency: 'Every 45 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400',
    description: 'Comfortable train service to popular beach destinations.',
    operator: 'National Rail',
    schedule: ['8:00 AM', '8:45 AM', '9:30 AM', '10:15 AM'],
  },
  {
    id: 8,
    route: 'Night Bus N12',
    type: 'Bus',
    from: 'Entertainment District',
    to: 'Residential Area',
    duration: '35 mins',
    price: '$4.00',
    frequency: 'Every 30 mins',
    status: 'Active',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=400',
    description: 'Safe and reliable night service for late-night travelers.',
    operator: 'City Transit',
    schedule: ['11:00 PM', '11:30 PM', '12:00 AM', '12:30 AM'],
  },
];